# Generated by Django 2.2.3 on 2019-07-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('work', models.CharField(max_length=30)),
                ('fnlwgt', models.IntegerField()),
                ('education', models.CharField(max_length=30)),
                ('education_num', models.IntegerField()),
                ('marital_status', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('relationship', models.IntegerField(choices=[(1, 'Husband'), (2, 'Wife'), (3, 'Own-child'), (4, 'Other-relative'), (5, 'Not-in-family'), (6, 'Unmarried')])),
                ('race', models.IntegerField(choices=[(1, 'White'), (2, 'Black'), (3, 'Asian-Pac-Islander'), (4, 'Amer-Indian-Eskimo'), (5, 'Other')])),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('capital_gain', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('native_country', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('salary_range', models.CharField(max_length=5)),
            ],
        ),
    ]
